name: continuos-deploymant
run-name: Deploy do app

on:
    push:
        - main

jobs: 
    deploy:
        name: deploy
        runs-on: ubuntu-24.04

        steps:
            - uses: actions/checkout@v4
              with:
                fetch-depth: 0

            - name: Docker login
              uses: docker/login-action@v3.4.0
              with:
                username: ${{ secrets.DOCKER_USER}}
                password: ${{ secrets.DOCKER_PASSWORD}}

            - name: Build and push Docker Image
              uses: docker/build-push-action@v6.15.0
              with:
                context: .
                file: ./Dockerfile
                push: true
                tags: joaoma12/site-facudade-b:latest

            - name: Azure app
              uses: Azure/webapps-deploy@v3.0.1
              with:
                app-name: SiteFacuQuirino
                image: joaoma12/site-facudade-b:latest
                publish-profile: ${{ secrets.PUBLISH_PROFILE }}