name: primeiro-workflow # nome tecnico
run-name: Meu Primeiro Workflow # nome descritivo

# on: [push] 
 
on: # evento 
    push:
        branches:
             - main

jobs:
    mac:
        runs-on: macos-latest
        steps:
            - name: Rodar um hello no mac
              run: echo "hello word"